ERROR | my_app | exception message.
Traceback (most recent call last):
  File "C:\Users\sammy\projects\portfolio\learn-logging\main.py", line 25, in main
    1/0
    ~^~
ZeroDivisionError: division by zero
DEBUG | my_app | debug message
INFO | my_app | info message
WARNING | my_app | warning message
ERROR | my_app | error message
CRITICAL | my_app | critical message
ERROR | my_app | exception message
Traceback (most recent call last):
  File "C:\Users\sammy\projects\portfolio\learn-logging\main.py", line 25, in main
    1/0
    ~^~
ZeroDivisionError: division by zero
DEBUG | main | 19 | 2025-10-19 15:07:06,592 | my_app | debug message
INFO | main | 20 | 2025-10-19 15:07:06,592 | my_app | info message
WARNING | main | 21 | 2025-10-19 15:07:06,635 | my_app | warning message
ERROR | main | 22 | 2025-10-19 15:07:06,635 | my_app | error message
CRITICAL | main | 23 | 2025-10-19 15:07:06,635 | my_app | critical message
ERROR | main | 27 | 2025-10-19 15:07:06,635 | my_app | exception message
Traceback (most recent call last):
  File "C:\Users\sammy\projects\portfolio\learn-logging\main.py", line 25, in main
    1/0
    ~^~
ZeroDivisionError: division by zero
DEBUG | main | 19 | 2025-10-19 15:08:59,548 | my_app | debug message
INFO | main | 20 | 2025-10-19 15:08:59,548 | my_app | info message
WARNING | main | 21 | 2025-10-19 15:08:59,548 | my_app | warning message
ERROR | main | 22 | 2025-10-19 15:08:59,548 | my_app | error message
CRITICAL | main | 23 | 2025-10-19 15:08:59,548 | my_app | critical message
ERROR | main | 27 | 2025-10-19 15:08:59,553 | my_app | exception message
Traceback (most recent call last):
  File "C:\Users\sammy\projects\portfolio\learn-logging\main.py", line 25, in main
    1/0
    ~^~
ZeroDivisionError: division by zero
[DEBUG|main|L19] 2025-10-19T15:11:39-0400: debug message
[INFO|main|L20] 2025-10-19T15:11:39-0400: info message
[WARNING|main|L21] 2025-10-19T15:11:39-0400: warning message
[ERROR|main|L22] 2025-10-19T15:11:39-0400: error message
[CRITICAL|main|L23] 2025-10-19T15:11:39-0400: critical message
[ERROR|main|L27] 2025-10-19T15:11:39-0400: exception message
Traceback (most recent call last):
  File "C:\Users\sammy\projects\portfolio\learn-logging\main.py", line 25, in main
    1/0
    ~^~
ZeroDivisionError: division by zero
